### ISSUE TITLE
GoogleVRについて

### ISSUE THREAD

**Issue by ghost** [oreilly-japan/unity-virtual-reality-projects-ja#1]
Unity5.5ではGoogleVRをいれてもVirtual Reality SDKsにCardboardが表示されません
<img width="440" alt="2017-01-05 12 18 48" src="https://cloud.githubusercontent.com/assets/6726734/21668021/3be0e6d2-d341-11e6-8e24-773c8d2e7029.png">

なのでGoogleVRは現在Unity5.5を使うとcardboardが利用できません、Daydream technical previewを使う必要があります、すいませんUnity5.4は未確認です
https://unity3d.com/jp/partners/google/daydream

**Comment by ktaka** [comment]
この場合、Cardboard用にビルドする際は**Virtual Reality Supported**のチェックは外して頂ければ大丈夫です。**Virtual Reality SDKs**の設定は不要になります。
Cardboard用にビルドする際に**Virtual Reality Supported**にチェックを入れるのは今のところDaydream Technical Preview版のUnityを使う場合のみで、Unityのバージョン5.5.xと5.4.xをお使いの場合は本書の51ページの「3.4.5 ビルドの設定」の手順に沿って進めて頂ければと思います。

**Comment by ghost** [comment]
ご回答ありがとうございます！

**Virtual Reality Supported**をチェックせずにビルドすると以下の二つのビルドエラーが発生しました

    Assets/GoogleVR/Scripts/Video/GvrVideoPlayerTexture.cs(595,7): error CS1622: Cannot return a value from iterators. Use the yield return statement to return a value, or yield break to end the iteration

こちらはGoogleVRのバグだと思うので、適切なもの返すように修正いたしました

    CommandInvokationFailure: Unable to merge android manifests. See the Console for more details. 

こちらはGoogleVRがビルド対象24なのにAndroidManifestが22だと言っていたのでplugin下のAndroidManifestのビルドバージョンを24に修正しました

    <uses-sdk android:minSdkVersion="19" android:targetSdkVersion="24" />

この二つを修正すると無事ビルドが通り実機で実行できました！
ご教授いただきありがとうございました！

**Comment by ktaka** [comment]
確かに1.10.0のGoogle VR SDK for Unityを使うと指摘頂いたエラーが出ますね。（1.0.3までは出ていなかったのですが...）
解決法も示して頂きありがとうございます！
